name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: cf356559-447f-4ef5-a596-5843ea2a66de
          region: East US
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions
      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: cf356559-447f-4ef5-a596-5843ea2a66de
          template: ./arm-templates/storageaccount.json
          parameters: 
            sku=Standard_LRS
            storageAccountName=globostg002di77
            location="East US"
          deploymentMode: incremental
      - name: Deploy Virtual Machine
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: cf356559-447f-4ef5-a596-5843ea2a66de
          template: ./arm-templates/virtualmachine.json
          parameters: 
            adminPassword=${{secrets.UBUNTU_ADMIN_PASSWORD}}
          deploymentMode: incremental

